apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-guide
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: 'lab-guide'
    server: 'https://kubernetes.default.svc'
  source:
    path: lab-guide/
    repoURL: 'https://rh-bjeon.github.io/mad-ops-acm/mad-ops-acm/main/m1-overview/setup.html'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
